language: swift
osx_image: xcode11

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - brew outdated carthage || brew upgrade carthage

env:
  global:
    - PROJECT=CollectionViewTools.xcodeproj
    - IOS_FRAMEWORK_SCHEME=CollectionViewTools
    - IOS_SDK=iphonesimulator

  matrix:
    - DESTINATION="OS=13.0,name=iPhone 11"

script:
  - set -o pipefail
  - carthage bootstrap --platform iOS
  - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" build test | xcpretty -c --test --color
