language: swift
osx_image: xcode10.2

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

env:
  global:
    - PROJECT=CollectionViewTools.xcodeproj
    - IOS_FRAMEWORK_SCHEME=CollectionViewTools
    - IOS_SDK=iphonesimulator

  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"
    - DESTINATION="OS=11.0.1,name=iPhone X"
    - DESTINATION="OS=12.0,name=iPhone XS Max"

script:
  - set -o pipefail
  - xcodebuild -project "$PROJECT" -scheme "$IOS_FRAMEWORK_SCHEME" -sdk "$IOS_SDK" -destination "$DESTINATION" build test | xcpretty -c --test --color
